Assets/Dardust_Movement.cs, Assets/Scenes/SampleScene.unity, Assets/Zelena_Movement.cs, ProjectSettings/TagManager.asset
Ho sistemato lo script di entrambi i personaggi, e ho sistemato il box collider del terreno.
=> Ottimizzati movimenti dardust e la puttana

Assets/Scenes/livello_2.unity, Assets/Scenes/livello_3.unity
Da sistemare il livello 3 perchè fatto con materiali non jumpabili, infatti durdust e zelena non si poggiano
=> Aggiunti personaggi

Assets/Scenes/livello_2.unity, Assets/Scenes/livello_3.unity
cosi puoi fare i livelli per bene amo (kiss)
=> inseriti corda, collider e personaggi in livello 2 e 3

Assets/Animazioni/Dardust_death.anim, Assets/Animazioni/Zelena_death.anim
Aggiunta dinamica morte e respawn dei giocatori automatico dopo l'animazione death
=> Aggiunta morti e respawn

Assets/Animazioni/Gemma_arancione.anim, Assets/Animazioni/Gemma_arancione.controller, Assets/Animazioni/Gemma_arancione.controller.meta, Assets/Animazioni/Gemma_gialla 1.controller, Assets/Animazioni/Gemma_gialla 1.controller.meta, Assets/Animazioni/Gemma_gialla.anim, Assets/Animazioni/Gemma_rossa 1.controller, Assets/Animazioni/Gemma_rossa 1.controller.meta, Assets/Animazioni/Gemma_rossa.anim, Assets/Gemmepazzwe/GIF_SpinningCoin.gif.meta, Assets/Gemmepazzwe/GIF_SpinningGem.gif.meta, Assets/Scenes/livello_1.unity, ProjectSettings/TagManager.asset
=> Messo per la seconda volta le nuove gemme

Assets/Script/ItemCollector.cs
Sistemate tutte le gemme collezionabili e aggiunto il counter
=> Finito counter gemme

Assets/Script/ItemCollector.cs
Reverts emanuele231/Tied_Up#38
=> Revert "Finito counter gemme"

Assets/Script/attacco_scheletrino.cs
Ho commentato la parte di codice che dava errore.
=> No safe mode

Assets/Scenes/livello_1.unity
Reso univoco il font per il conteggio gemme con il conteggio del punteggio
=> Correzione font testo gemme

Assets/Scenes/livello_1.unity, Assets/Scenes/livello_2.unity, Assets/Script/Dardust_Movement.cs, Assets/Script/Zelena_Movement.cs, ProjectSettings/TagManager.asset
Aggiornato in tutti i livelli Durdust e zelena che si possono saltare. In più sistemato in ogni livello la porcaccia madonna di barra superiore. Ora è uguale e funziona in tutti i livelli.
=> Il god supremo

Assets/Script/Rope.cs
non ci credo ci sono riuscito mi sento un drago
=> implementato trascinamento

Assets/Scenes/livello_1.unity, Assets/Scenes/livello_2.unity, Assets/Script/ItemCollector.cs, Assets/Script/end_level.cs, ProjectSettings/TagManager.asset
se arrivano alla porta con meno di 3 gemme la trovano sbarrata se no la trovano aperta
=> aggiunto il controllo sul completamento del livello

Assets/Scenes/livello_1.unity, Assets/Script/ItemCollector.cs, Assets/Script/end_level.cs, Assets/Script/traguardo.cs, Assets/Script/traguardo.cs.meta, ProjectSettings/TagManager.asset
ATTENZIONE: PRIMA FATE IL PULL DEL MASTER POI MERGIATE QUESTA. E' IMPORTANTE!!!!!!
=> aggiunto uscita del livello e risolto il bug delle gemme

Assets/Scenes/livello_1.unity, Assets/Scenes/risultati_1.unity, Assets/Scenes/risultati_1.unity.meta, Assets/Scenes/risultati_2.unity, Assets/Scenes/risultati_2.unity.meta, Assets/Scenes/risultati_3.unity, Assets/Scenes/risultati_3.unity.meta, Assets/Script/Traguardo_2.cs, Assets/Script/Traguardo_2.cs.meta, Assets/Script/trag_3.cs, Assets/Script/trag_3.cs.meta, Assets/Script/traguardo.cs, ProjectSettings/EditorBuildSettings.asset
mancano meccaniche di punti, tempo e monete da mettere, poi le metto perche mo ho statistica
=> inserite scene di riepilogo livello

Assets/SCRIPT/score_progress.cs, Assets/Scenes/livello_1.unity, Assets/Scenes/risultati_1.unity, Assets/Scenes/risultati_2.unity, Assets/Scenes/risultati_3.unity, Assets/Script/Zelena_life.cs, Assets/Script/end_level.cs, Assets/Script/punteggio_TOT1.cs, Assets/Script/punteggio_TOT1.cs.meta
mancano monete, checkpoint e l'eliminazione del delay dopo il respawn
=> sistemati punteggi e inseriti nelle scene dei risultati

Assets/ANIMAZIONI/Camminata_nemici.anim, Assets/ANIMAZIONI/Camminata_nemici.anim.meta, Assets/ANIMAZIONI/Skeletrino_fermo.anim, Assets/ANIMAZIONI/Skeletrino_fermo.anim.meta, Assets/ANIMAZIONI/scheletro_oscuro.controller, Assets/ANIMAZIONI/scheletro_oscuro.controller.meta, Assets/Beaviour_skeleton.cs, Assets/Beaviour_skeleton.cs.meta
Succede qualcosa, tutto da aggiustare
=> Primo tentativo

Assets/SCRIPT/score_progress.cs, Assets/Scenes/livello_1.unity, Assets/Scenes/risultati_1.unity, Assets/Scenes/risultati_2.unity, Assets/Scenes/risultati_3.unity, Assets/Script/monete.cs, Assets/Script/monete.cs.meta, Assets/Script/timer_menu.cs, Assets/Script/timer_menu.cs.meta
ho avuto problemi col punteggi ai risultati che dopo 30 secondi i punti calavano cosi ho insabbiato la cosa e ho messo il fatto che dopo 30 secondi fa lo switch automatico e torna indietro al menu
=> sistemati punteggio e monete

Assets/Scenes/livello_1.unity, Assets/Script/PauseController.cs, Assets/Script/PauseController.cs.meta, Assets/Script/restart.cs, Assets/Script/restart.cs.meta
=> inserita pausa

Assets/Scenes/livello_1.unity, Assets/Script/pause.cs
boh prima la pausa funzionava mo non funziona più, bentornati a MAP
=> boh ho fatto qualcosa

Assets/Scenes/livello_1.unity, Assets/Script/pause.cs
la pausa è magicamente ritornata tranne al livello 2 che non a caso non funziona
=> la pausa ce

Assets/Scenes/livello_1.unity, Assets/Script/Abbandona.cs, Assets/Script/Abbandona.cs.meta, Assets/Script/Restart.cs, Assets/Script/Restart.cs.meta, Assets/Script/pause.cs
=> pausa finita

Assets/ANIMAZIONI/Attacco_scheletro.anim, Assets/ANIMAZIONI/Attacco_scheletro.anim.meta, Assets/ANIMAZIONI/scheletro_oscuro.controller, Assets/SCRIPT/Sheletrini.cs, Assets/Scenes/livello_1.unity
Sistemata animazione scheletro che attacca quando tocca dardust o zelena
=> animazione attacco scheletro

Assets/ANIMAZIONI/Attacco_Zelena.anim, Assets/ANIMAZIONI/Attacco_Zelena.anim.meta, Assets/ANIMAZIONI/Dardust_Attacco.anim, Assets/Animazioni/Zelena.controller, Assets/SCRIPT/Sheletrini.cs, Assets/Scenes/livello_1.unity, Assets/Script/Arma_dardast.cs, Assets/Script/Zelena_Movement.cs, Assets/Script/arma_zelena.cs, ProjectSettings/InputManager.asset, ProjectSettings/QualitySettings.asset
Sicuramente ho messo che zelena spara perpendicolare e non più a cazzo floscio.. Poi non mi ricordo
=> varie modifiche non so manco io

Assets/SFONDO E INTRO/sequenza_introTimeline.playable, Assets/Scenes/introduzione.unity, ProjectSettings/EditorBuildSettings.asset
manca tasto esci dal gioco e sistemare il panel
=> inserito tasto skip per l'intro e impostata la sequenza delle scene

Assets/ANIMAZIONI/Dardust_Attacco.anim, Assets/Animazioni/Dardast.controller, Assets/Animazioni/Zelena.controller, Assets/Scenes/livello_1.unity, Assets/Script/Arma_dardast.cs
ho messo l'animazione a dardust mo che attacca
=> mo succede un casino

Assets/Scenes/livello_1.unity, Assets/Script/ItemCollector.cs, Assets/Script/Rope.cs
=> inserito recupero vita

Assets/SCRIPT/score_progress.cs, Assets/Scenes/livello_1.unity
ho spostato i 2 trimoni perchè dovevo provare se si strozzavano
=> punteggi sistemati

Assets/Scenes/livello_1.unity, Assets/Script/Arma_dardast.cs, Assets/Script/arma_zelena.cs
=> Non so manco che modifiche ho fatto

Assets/SCRIPT/Sheletrini.cs, Assets/Script/arma_zelena.cs
porcala puttana mo funziona quella troia
=> sistemata szelena

Assets/MATERIALI E PERSONAGGI/DARDUST AND ZELENA/Zelena.prefab, Assets/Scenes/livello_1.unity, Assets/Videocamera.cs, Assets/Videocamera.cs.meta, ProjectSettings/TagManager.asset
Non sta più attaccata al culo di zelena dio cane
=> Telecamera

Assets/Script/Zelena_Movement.cs, Assets/Script/arma_zelena.cs
=> Inserita animaizone

Assets/SCRIPT/Sheletrini.cs
=> Livello 2 completo
